name: CD Pipeline

on:
  # push:
  #   branches:
  #     - main
      
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy (default: main)'
        required: false
        default: 'main'
      repository-uri:
        description: 'ECR repository URI (e.g. 123456789012.dkr.ecr.us-west-2.amazonaws.com/my-repo)'
        required: true
      aws-region:
        description: 'AWS region to use'
        required: false
        default: 'ap-northeast-2'

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

  ecr_login:
    uses: oyg-pf-dev-prep/github-action/.github/workflows/ecr-login-v1.yaml@main
    with:
      repository-uri: ${{ inputs.repository-uri }}
      region: ${{ inputs.aws-region }}

  setup_jib:
    uses: oyg-pf-dev-prep/github-action/.github/workflows/setup-jib-v1.yaml@main

  build_and_push_image:
    runs-on: ubuntu-latest
    needs: [checkout, ecr_login, setup_jib]
    steps:
      - name: Build & Push to ECR
        run: |
          jib build -b jib.yaml --to=${{ inputs.repository-uri }}
