name: CD Pipeline

on:
  # push:
  #   branches:
  #     - main
      
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy (default: main)'
        required: false
        default: 'main'

jobs:
  input_check:
    runs-on: ubuntu-latest
    steps:
      - name: echo inputs
        run: |
          echo ${{ inputs.branch }}

  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

  ecr_login:
    permissions:
      id-token: write  # OIDC 토큰을 요청할 수 있도록 권한을 설정
      contents: read   # actions/checkout을 위한 권한
    uses: oyg-pf-dev-prep/github-action/.github/workflows/ecr-login-v1.yaml@main

  setup_jib:
    uses: oyg-pf-dev-prep/github-action/.github/workflows/setup-jib-v1.yaml@main

  build_and_push_image:
    runs-on: ubuntu-latest
    needs: [checkout, ecr_login, setup_jib]
    steps:
      - name: Build & Push to ECR
        run: |
          jib build -b jib.yaml --target=${{ needs.ecr_login.outputs.repository-uri }}
