name: CD Pipeline

on:
  push:
    branches:
      - main
      
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy (default: main)'
        required: false
        default: 'main'
      repository-uri:
        description: 'ECR repository URI (e.g. 123456789012.dkr.ecr.us-west-2.amazonaws.com/my-repo)'
        required: true
      aws-region:
        description: 'AWS region to use'
        required: false
        default: 'ap-northeast-2'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Ecr login
        uses: oyg-pf-dev-prep/github-actions/.github/workflows/ecr-login-v1@main
        with:
          repository-uri: ${{ inputs.repository-uri }}
          region: ${{ inputs.aws-region }}

      - name: Setup jib
        uses: oyg-pf-dev-prep/github-actions/.github/workflows/setup-jib-v1@main

      - name: Build & Push to ECR
        run: |
          jib build -b jib.yaml --to=${{ inputs.repository-uri }}
